SELECT 
    REQUESTEDIMPLEMENTATIONDATE, 
    TASKRECEIVEDDATE, 
    UPDATEDOBJECTNAME, 
    UPDATEDOBJECTNUMBER, 
    IMPLEMENTATIONREQSUPPLIERID, 
    UPDATEDOBJECTVERSION, 
    UPDATEDOBJECTTYPE, 
    ARTICLENAME, 
    ARTICLENUMBER, 
    ITEMTYPE, 
    TASKRECEIVEDDATE, 
    PLANNEDIMPLEMENTATIONDATE, 
    CONNECTEDEXCEPTIONS, 
    MESSAGETOSUPPLIER, 
    IRNUMBER 
FROM 
    PDMLINK.SUPPLIER_TASK_DETAILS_CACHE    
WHERE 
    TASKOWNER = LOWER('plustest41') 
    AND TASKNAME = 'Send Request for Implementation' 
    AND TASKVIEW = 'ITEM' 
    AND TASKSTATUS = 'OPEN' 
    AND ISUNDERGOINGCHANGES = 0;

    select distinct(taskname) from  PDMLINK.SUPPLIER_TASK_DETAILS_CACHE  ;

    select * from PDMLINK.SUPPLIER_TASK_DETAILS_CACHE where IRNUMBER = 'IR0004209444'  and TASKSTATUS = 'OPEN';



SELECT  REQUESTEDIMPLEMENTATIONDATE, TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, ARTICLENAME, ARTICLENUMBER, ITEMTYPE, TASKRECEIVEDDATE, PLANNEDIMPLEMENTATIONDATE, CONNECTEDEXCEPTIONS, MESSAGETOSUPPLIER, IRNUMBER, BASEPRODUCTOID,PACKAGINGPARTOID, EFFCONTEXTOID 
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE 
TASKOWNER='plustest41' and TASKNAME='Send Request for Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0'
 
SELECT  IRNUMBER, REQUESTEDIMPLEMENTATIONDATE, BASEPRODUCTOID,PACKAGINGPARTOID, EFFCONTEXTOID, IMPLEMENTATIONREQSUPPLIERID 
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE 
TASKOWNER='plustest41' and TASKNAME='Send Request for Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0'
 

SELECT IRNUMBER, REQUESTEDIMPLEMENTATIONDATE, BASEPRODUCTOID,PACKAGINGPARTOID, EFFCONTEXTOID, IMPLEMENTATIONREQSUPPLIERID 
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE
WHERE TASKOWNER='plustest41' and TASKNAME='Send Request for Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0'


SELECT REQUESTEDIMPLEMENTATIONDATE, TASKRECEIVEDDATE, UPDATEDOBJECTNAME,
              UPDATEDOBJECTNUMBER, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION,
              UPDATEDOBJECTTYPE, ARTICLENAME, ARTICLENUMBER, ITEMTYPE,
              TASKRECEIVEDDATE, PLANNEDIMPLEMENTATIONDATE, CONNECTEDEXCEPTIONS,
              MESSAGETOSUPPLIER, IRNUMBER
        FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE
WHERE TASKOWNER='plustest21' and TASKNAME='Send Request for Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0'
ORDER BY IRNUMBER;

SELECT IRNUMBER, REQUESTEDIMPLEMENTATIONDATE, BASEPRODUCTOID,PACKAGINGPARTOID, EFFCONTEXTOID, IMPLEMENTATIONREQSUPPLIERID 
        FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE
        WHERE TASKOWNER='plustest41' and TASKNAME='Send Request for Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0'
ORDER BY IRNUMBER;

SELECT 
ITEMTYPE, 
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE, IRNUMBER,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER, UPDATEDOBJECTOID,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKOWNER='plustest21' and TASKNAME='Review Implementation Request' and TASKVIEW='ITEM' and 
TASKSTATUS IN ('OPEN') and ISUNDERGOINGCHANGES='0' and CANCELLATIONREQUESTED='0'