/* --Purchasing Portal
 New IR: - Item, Part, Specification(PLEASE provide this values for taskview) Engineer mode */
SELECT ITEMTYPE,
ACTUALIMPLEMENTATIONDATE,REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, PRODUCTNAME, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, UPDATEDOBJECTOID,
ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER,IRNUMBER 
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE WHERE 
TASKOWNER='plustest41' and TASKNAME='Send Request for Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0'

-- Ongoing - Item, Part, Specification(PLEASE provide this values for taskview) Engineer mode
SELECT ITEMTYPE,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
UPDATEDOBJECTOID, ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER, IRNUMBER FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE WHERE 
TASKNAME IN ('Review Implementation Request', 'Confirm Implementation') and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES IN ('0','1')
Group by ITEMTYPE,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
UPDATEDOBJECTOID, ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER, IRNUMBER

-- Implemented - Item, Part, Specification(PLEASE provide this values for taskview) Engineer mode
SELECT ITEMTYPE,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER,
IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
UPDATEDOBJECTOID, ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER, IRNUMBER FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE WHERE 
TASKNAME='Confirm Implementation' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ROUTINGOPTION='Implemented' and Status IS NULL
Group By ITEMTYPE,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER,
IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
UPDATEDOBJECTOID, ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER, IRNUMBER


--Revision Request - Item, Part, Specification(PLEASE provide this values for taskview) Engineer mode
select ITEMTYPE, MESSAGETOSUPPLIER,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, 
PLANNEDIMPLEMENTATIONDATE,UPDATEDOBJECTNAME, UPDATEDOBJECTOID,
TASKRECEIVEDDATE, UPDATEDOBJECTNUMBER, CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, 
UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, ARTICLENAME, 
ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, REQUESTEDNEWIMPLDATE, IRNUMBER
from PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKOWNER='plustest41'  and TASKNAME='Date Change Request for Purchasing Team' and 
TASKVIEW='ITEM' and TASKSTATUS='OPEN'


-- Cancellation Request - Item, Part, Specification(PLEASE provide this values for taskview) Engineer mode
SELECT 
ITEMTYPE, MESSAGETOSUPPLIER,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE,  PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNUMBER, CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, 
UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, UPDATEDOBJECTNAME, UPDATEDOBJECTOID, ARTICLENAME, 
ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, IRNUMBER
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKNAME='Cancellation Request' and TASKVIEW='ITEM' and 
TASKSTATUS='OPEN' and CANCELLATIONREQUESTED='1'
GROUP BY ITEMTYPE, MESSAGETOSUPPLIER,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE,  PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNUMBER, CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, 
UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, UPDATEDOBJECTNAME, UPDATEDOBJECTOID, ARTICLENAME, 
ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, IRNUMBER


/* Supplier Portal
New IR - Item, Part, Specification(PLEASE provide this values for taskview) Signer mode */

SELECT 
ITEMTYPE, 
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE, IRNUMBER,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER, UPDATEDOBJECTOID,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKOWNER='plustest21' and TASKNAME='Review Implementation Request' and TASKVIEW='ITEM' and 
TASKSTATUS IN ('OPEN') and ISUNDERGOINGCHANGES='0' and CANCELLATIONREQUESTED='0'

-- Ongoing - Item, Part, Specification(PLEASE provide this values for taskview) Signer mode
SELECT 
ITEMTYPE, 
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE, IRNUMBER, 
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER, UPDATEDOBJECTOID,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID,MESSAGETOSUPPLIER
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKOWNER='plustest21' and TASKNAME='Confirm Implementation' and TASKVIEW='ITEM' and 
TASKSTATUS='OPEN' and ISUNDERGOINGCHANGES='0' and CANCELLATIONREQUESTED='0'

-- Implemented - Item, Part, Specification(PLEASE provide this values for taskview) Signer mode
SELECT ITEMTYPE,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER, UPDATEDOBJECTOID,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER,IRNUMBER FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE WHERE 
TASKNAME='plustest21' and TASKVIEW='ITEM' and TASKSTATUS='OPEN' and ROUTINGOPTION='Implemented'

--Revision Request - Item, Part, Specification(PLEASE provide this values for taskview) Signer mode
SELECT 
MESSAGETOSUPPLIER,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE, IRNUMBER,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
UPDATEDOBJECTOID, ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, REQUESTEDNEWIMPLDATE, MESSAGETOSUPPLIER 
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKOWNER='plustest21'  and TASKNAME IN('Confirm Implementation','Review Implementation Request') and TASKVIEW='ITEM' and 
TASKSTATUS IN ('OPEN','CLOSED') and ISUNDERGOINGCHANGES='1'

--Cancellation Request - Item, Part, Specification(PLEASE provide this values for taskview) Signer mode
SELECT 
MESSAGETOSUPPLIER,
ACTUALIMPLEMENTATIONDATE, REQUESTEDIMPLEMENTATIONDATE, PLANNEDIMPLEMENTATIONDATE, IRNUMBER,
TASKRECEIVEDDATE, UPDATEDOBJECTNAME, UPDATEDOBJECTNUMBER, UPDATEDOBJECTOID,
CONNECTEDEXCEPTIONS, IMPLEMENTATIONREQSUPPLIERID, UPDATEDOBJECTVERSION, UPDATEDOBJECTTYPE, 
ARTICLENAME, ARTICLENUMBER, BASEPRODUCTOID, PACKAGINGPARTOID, EFFCONTEXTOID, MESSAGETOSUPPLIER
FROM PDMLINK.SUPPLIER_TASK_DETAILS_CACHE 
WHERE TASKOWNER='plustest21' and TASKNAME='Cancellation Request' and TASKVIEW='ITEM' and 
TASKSTATUS='OPEN' and CANCELLATIONREQUESTED='1'
